export const characterRoles = [
  { value: "man", label: "Man", exists: true },
  { value: "woman", label: "Woman", exists: true },
  { value: "hero", label: "Hero", exists: true },
  { value: "heroine", label: "Heroine", exists: true },
  { value: "villain", label: "Villain", exists: true },
  { value: "protagonist", label: "Protagonist", exists: true },
  { value: "antagonist", label: "Antagonist", exists: true },
  { value: "sidekick", label: "Sidekick", exists: true },
  { value: "mentor", label: "Mentor", exists: true },
  { value: "love_interest", label: "Love Interest", exists: true },
  { value: "parent", label: "Parent", exists: true },
  { value: "child", label: "Child", exists: true },
  { value: "sibling", label: "Sibling", exists: true },
  { value: "best_friend", label: "Best Friend", exists: true },
  { value: "detective", label: "Detective", exists: true },
  { value: "police_officer", label: "Police Officer", exists: true },
  { value: "lawyer", label: "Lawyer", exists: true },
  { value: "doctor", label: "Doctor", exists: true },
  { value: "scientist", label: "Scientist", exists: true },
  { value: "teacher", label: "Teacher", exists: true },
  { value: "student", label: "Student", exists: true },
  { value: "soldier", label: "Soldier", exists: true },
  { value: "spy", label: "Spy", exists: true },
  { value: "pirate", label: "Pirate", exists: true },
  { value: "cowboy", label: "Cowboy", exists: true },
  { value: "cowgirl", label: "Cowgirl", exists: true },
  { value: "outlaw", label: "Outlaw", exists: true },
  { value: "king", label: "King", exists: true },
  { value: "queen", label: "Queen", exists: true },
  { value: "prince", label: "Prince", exists: true },
  { value: "princess", label: "Princess", exists: true },
  { value: "emperor", label: "Emperor", exists: true },
  { value: "empress", label: "Empress", exists: true },
  { value: "knight", label: "Knight", exists: true },
  { value: "wizard", label: "Wizard", exists: true },
  { value: "witch", label: "Witch", exists: true },
  { value: "fairy", label: "Fairy", exists: true },
  { value: "elf", label: "Elf", exists: true },
  { value: "dwarf", label: "Dwarf", exists: true },
  { value: "vampire", label: "Vampire", exists: true },
  { value: "werewolf", label: "Werewolf", exists: true },
  { value: "ghost", label: "Ghost", exists: true },
  { value: "zombie", label: "Zombie", exists: true },
  { value: "monster", label: "Monster", exists: true },
  { value: "alien", label: "Alien", exists: true },
  { value: "robot", label: "Robot", exists: true },
  { value: "cyborg", label: "Cyborg", exists: true },
  { value: "superhero", label: "Superhero", exists: true },
  { value: "supervillain", label: "Supervillain", exists: true },
  { value: "athlete", label: "Athlete", exists: true },
  { value: "musician", label: "Musician", exists: true },
  { value: "actor", label: "Actor", exists: true },
  { value: "artist", label: "Artist", exists: true },
  { value: "writer", label: "Writer", exists: true },
  { value: "explorer", label: "Explorer", exists: true },
  { value: "adventurer", label: "Adventurer", exists: true },
  { value: "sailor", label: "Sailor", exists: true },
  { value: "pilot", label: "Pilot", exists: true },
  { value: "astronaut", label: "Astronaut", exists: true },
  { value: "engineer", label: "Engineer", exists: true },
  { value: "inventor", label: "Inventor", exists: true },
  { value: "businessperson", label: "Businessperson", exists: true },
  { value: "entrepreneur", label: "Entrepreneur", exists: true },
  { value: "politician", label: "Politician", exists: true },
  { value: "president", label: "President", exists: true },
  { value: "prime_minister", label: "Prime Minister", exists: true },
  { value: "dictator", label: "Dictator", exists: true },
  { value: "rebel", label: "Rebel", exists: true },
  { value: "revolutionary", label: "Revolutionary", exists: true },
  { value: "survivor", label: "Survivor", exists: true },
  { value: "orphan", label: "Orphan", exists: true },
  { value: "refugee", label: "Refugee", exists: true },
  { value: "immigrant", label: "Immigrant", exists: true },
  { value: "royalty", label: "Royalty", exists: true },
  { value: "servant", label: "Servant", exists: true },
  { value: "maid", label: "Maid", exists: true },
  { value: "butler", label: "Butler", exists: true },
  { value: "gardener", label: "Gardener", exists: true },
  { value: "chef", label: "Chef", exists: true },
  { value: "waiter", label: "Waiter", exists: true },
  { value: "waitress", label: "Waitress", exists: true },
  { value: "bartender", label: "Bartender", exists: true },
  { value: "nurse", label: "Nurse", exists: true },
  { value: "patient", label: "Patient", exists: true },
  { value: "criminal", label: "Criminal" },
  { value: "gangster", label: "Gangster" },
  { value: "thug", label: "Thug" },
  { value: "con_artist", label: "Con Artist" },
  { value: "gambler", label: "Gambler" },
  { value: "thief", label: "Thief" },
  { value: "robber", label: "Robber" },
  { value: "assassin", label: "Assassin" },
  { value: "mercenary", label: "Mercenary" },
  { value: "barbarian", label: "Barbarian" },
  { value: "gladiator", label: "Gladiator" },
  { value: "slave", label: "Slave" },
  { value: "master", label: "Master" },
  { value: "teacher", label: "Teacher" },
  { value: "student", label: "Student" },
  { value: "professor", label: "Professor" },
  { value: "scholar", label: "Scholar" },
  { value: "librarian", label: "Librarian" },
  { value: "historian", label: "Historian" },
];
