export const characterRoles = [
  { value: "man", label: "Man" },
  { value: "woman", label: "Woman" },
  { value: "athlete", label: "Athlete" },
  { value: "musician", label: "Musician" },
  { value: "actor", label: "Actor" },
  { value: "artist", label: "Artist" },
  { value: "entrepreneur", label: "Entrepreneur" },
  { value: "dictator", label: "Dictator" },
  { value: "rebel", label: "Rebel" },
  { value: "survivor", label: "Survivor" },
  { value: "refugee", label: "Refugee" },
  { value: "royalty", label: "Royalty" },
  { value: "criminal", label: "Criminal" },
  { value: "thug", label: "Thug" },
  { value: "gambler", label: "Gambler" },
  { value: "assassin", label: "Assassin" },
  { value: "barbarian", label: "Barbarian" },
  { value: "gladiator", label: "Gladiator" },
  { value: "slave", label: "Slave" },
  { value: "professor", label: "Professor" },
  { value: "librarian", label: "Librarian" },
];
