export const places = [
    { value: "United States", label: "United States" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "France", label: "France" },
    { value: "Germany", label: "Germany" },
    { value: "Italy", label: "Italy" },
    { value: "Russia", label: "Russia" },
    { value: "China", label: "China" },
    { value: "Japan", label: "Japan" },
    { value: "India", label: "India" },
    { value: "Brazil", label: "Brazil" },
    { value: "Canada", label: "Canada" },
    { value: "Australia", label: "Australia" },
    { value: "Spain", label: "Spain" },
    { value: "Mexico", label: "Mexico" },
    { value: "Argentina", label: "Argentina" },
    { value: "Egypt", label: "Egypt" },
    { value: "Greece", label: "Greece" },
    { value: "Turkey", label: "Turkey" },
    { value: "South Africa", label: "South Africa" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Kenya", label: "Kenya" },
    { value: "Ghana", label: "Ghana" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Morocco", label: "Morocco" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Israel", label: "Israel" },
    { value: "Palestine", label: "Palestine" },
    { value: "Syria", label: "Syria" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Jordan", label: "Jordan" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "Qatar", label: "Qatar" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Oman", label: "Oman" },
    { value: "Yemen", label: "Yemen" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Nepal", label: "Nepal" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Thailand", label: "Thailand" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Singapore", label: "Singapore" },
    { value: "Philippines", label: "Philippines" },
    { value: "South Korea", label: "South Korea" },
    { value: "North Korea", label: "North Korea" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Myanmar (Burma)", label: "Myanmar (Burma)" },
    { value: "Laos", label: "Laos" },
    { value: "Brunei", label: "Brunei" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Fiji", label: "Fiji" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Solomon Islands", label: "Solomon Islands" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Samoa", label: "Samoa" },
    { value: "Tonga", label: "Tonga" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Marshall Islands", label: "Marshall Islands" },
    { value: "Micronesia", label: "Micronesia" },
    { value: "Palau", label: "Palau" },
    { value: "Nauru", label: "Nauru" },
    { value: "Cook Islands", label: "Cook Islands" },
    { value: "Niue", label: "Niue" },
    { value: "Tokelau", label: "Tokelau" },
    { value: "American Samoa", label: "American Samoa" },
    { value: "Guam", label: "Guam" },
    { value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
    { value: "Wallis and Futuna", label: "Wallis and Futuna" },
    { value: "French Polynesia", label: "French Polynesia" },
    { value: "Pitcairn Islands", label: "Pitcairn Islands" }
  ];
  