export const places = [
  { value: "United States", label: "United States", exists: true },
  { value: "United Kingdom", label: "United Kingdom", exists: true },
  { value: "France", label: "France", exists: true },
  { value: "Germany", label: "Germany", exists: true },
  { value: "Italy", label: "Italy", exists: true },
  { value: "Russia", label: "Russia", exists: true },
  { value: "China", label: "China", exists: true },
  { value: "Japan", label: "Japan", exists: true },
  { value: "India", label: "India", exists: true },
  { value: "Brazil", label: "Brazil", exists: true },
  { value: "Canada", label: "Canada", exists: true },
  { value: "Australia", label: "Australia", exists: true },
  { value: "Spain", label: "Spain", exists: true },
  { value: "Mexico", label: "Mexico", exists: true },
  { value: "Argentina", label: "Argentina", exists: true },
  { value: "Egypt", label: "Egypt", exists: true },
  { value: "Greece", label: "Greece", exists: true },
  { value: "Turkey", label: "Turkey", exists: true },
  { value: "South Africa", label: "South Africa", exists: true },
  { value: "Nigeria", label: "Nigeria", exists: true },
  { value: "Kenya", label: "Kenya", exists: true },
  { value: "Ghana", label: "Ghana", exists: true },
  { value: "Ethiopia", label: "Ethiopia", exists: true },
  { value: "Morocco", label: "Morocco", exists: true },
  { value: "Saudi Arabia", label: "Saudi Arabia", exists: true },
  { value: "Iran", label: "Iran", exists: true },
  { value: "Iraq", label: "Iraq", exists: true },
  { value: "Israel", label: "Israel", exists: true },
  { value: "Palestine", label: "Palestine", exists: true },
  { value: "Syria", label: "Syria", exists: true },
  { value: "Lebanon", label: "Lebanon", exists: true },
  { value: "Jordan", label: "Jordan", exists: true },
  {
    value: "United Arab Emirates",
    label: "United Arab Emirates",
    exists: true,
  },
  { value: "Qatar", label: "Qatar", exists: true },
  { value: "Kuwait", label: "Kuwait", exists: true },
  { value: "Bahrain", label: "Bahrain", exists: true },
  { value: "Oman", label: "Oman", exists: true },
  { value: "Yemen", label: "Yemen", exists: true },
  { value: "Afghanistan", label: "Afghanistan", exists: true },
  { value: "Pakistan", label: "Pakistan", exists: true },
  { value: "Bangladesh", label: "Bangladesh", exists: true },
  { value: "Sri Lanka", label: "Sri Lanka", exists: true },
  { value: "Nepal", label: "Nepal", exists: true },
  { value: "Bhutan", label: "Bhutan", exists: true },
  { value: "Thailand", label: "Thailand", exists: true },
  { value: "Vietnam", label: "Vietnam", exists: true },
  { value: "Cambodia", label: "Cambodia", exists: true },
  { value: "Indonesia", label: "Indonesia", exists: true },
  { value: "Malaysia", label: "Malaysia", exists: true },
  { value: "Singapore", label: "Singapore", exists: true },
  { value: "Philippines", label: "Philippines", exists: true },
  { value: "South Korea", label: "South Korea", exists: true },
  { value: "North Korea", label: "North Korea", exists: true },
  { value: "Mongolia", label: "Mongolia", exists: true },
  { value: "Kazakhstan", label: "Kazakhstan", exists: true },
  { value: "Uzbekistan", label: "Uzbekistan", exists: true },
  { value: "Tajikistan", label: "Tajikistan", exists: true },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", exists: true },
  { value: "Turkmenistan", label: "Turkmenistan", exists: true },
  { value: "Myanmar (Burma)", label: "Myanmar (Burma)", exists: true },
  { value: "Laos", label: "Laos", exists: true },
  { value: "Brunei", label: "Brunei", exists: true },
  { value: "Papua New Guinea", label: "Papua New Guinea", exists: true },
  { value: "Fiji", label: "Fiji", exists: true },
  { value: "New Zealand", label: "New Zealand", exists: true },
  { value: "Solomon Islands", label: "Solomon Islands", exists: true },
  { value: "Vanuatu", label: "Vanuatu", exists: true },
  { value: "Samoa", label: "Samoa", exists: true },
  { value: "Tonga", label: "Tonga", exists: true },
  { value: "Kiribati", label: "Kiribati", exists: true },
  { value: "Tuvalu", label: "Tuvalu", exists: true },
  { value: "Marshall Islands", label: "Marshall Islands", exists: true },
  { value: "Micronesia", label: "Micronesia", exists: true },
  { value: "Palau", label: "Palau", exists: true },
  { value: "Nauru", label: "Nauru", exists: true },
  { value: "Cook Islands", label: "Cook Islands", exists: true },
  { value: "Niue", label: "Niue", exists: true },
  { value: "Tokelau", label: "Tokelau", exists: true },
  { value: "American Samoa", label: "American Samoa", exists: true },
  { value: "Guam", label: "Guam", exists: true },
  {
    value: "Northern Mariana Islands",
    label: "Northern Mariana Islands",
    exists: true,
  },
  { value: "Wallis and Futuna", label: "Wallis and Futuna", exists: true },
  { value: "French Polynesia", label: "French Polynesia", exists: true },
  { value: "Pitcairn Islands", label: "Pitcairn Islands", exists: true },
  { value: "New York City", label: "New York City", exists: true },
  { value: "Paris", label: "Paris", exists: true },
  { value: "London", label: "London", exists: true },
  { value: "Rome", label: "Rome", exists: true },
  { value: "Tokyo", label: "Tokyo", exists: true },
  { value: "Los Angeles", label: "Los Angeles", exists: true },
  { value: "Berlin", label: "Berlin", exists: true },
  { value: "Moscow", label: "Moscow", exists: true },
  { value: "Sydney", label: "Sydney", exists: true },
  { value: "Istanbul", label: "Istanbul", exists: true },
  { value: "Mumbai", label: "Mumbai", exists: true },
  { value: "Cairo", label: "Cairo", exists: true },
  { value: "Buenos Aires", label: "Buenos Aires", exists: true },
  { value: "Rio de Janeiro", label: "Rio de Janeiro", exists: true },
  { value: "Beijing", label: "Beijing", exists: true },
  { value: "Athens", label: "Athens", exists: true },
  { value: "Barcelona", label: "Barcelona", exists: true },
  { value: "Amsterdam", label: "Amsterdam", exists: true },
  { value: "Dublin", label: "Dublin", exists: true },
  { value: "Prague", label: "Prague", exists: true },
  { value: "Vienna", label: "Vienna", exists: true },
  { value: "Florence", label: "Florence", exists: true },
  { value: "Jerusalem", label: "Jerusalem", exists: true },
  { value: "Edinburgh", label: "Edinburgh", exists: true },
  { value: "Cape Town", label: "Cape Town", exists: true },
  { value: "Venice", label: "Venice", exists: true },
  { value: "San Francisco", label: "San Francisco", exists: true },
  { value: "Havana", label: "Havana", exists: true },
  { value: "Stockholm", label: "Stockholm", exists: true },
  { value: "Bangkok", label: "Bangkok", exists: true },
  { value: "Seoul", label: "Seoul", exists: true },
  { value: "Mexico City", label: "Mexico City", exists: true },
  { value: "Montreal", label: "Montreal", exists: true },
  { value: "New Orleans", label: "New Orleans", exists: true },
  { value: "Shanghai", label: "Shanghai", exists: true },
  { value: "Budapest", label: "Budapest", exists: true },
  { value: "Delhi", label: "Delhi", exists: true },
  { value: "Lima", label: "Lima", exists: true },
  { value: "Santiago", label: "Santiago", exists: true },
  { value: "Copenhagen", label: "Copenhagen", exists: true },
  { value: "Warsaw", label: "Warsaw", exists: true },
  { value: "Beirut", label: "Beirut", exists: true },
  { value: "Nairobi", label: "Nairobi", exists: true },
  { value: "Reykjavik", label: "Reykjavik", exists: true },
  { value: "Melbourne", label: "Melbourne", exists: true },
  { value: "Auckland", label: "Auckland", exists: true },
  { value: "Oslo", label: "Oslo", exists: true },
  { value: "Zurich", label: "Zurich", exists: true },
  { value: "Toronto", label: "Toronto", exists: true },
  { value: "Marrakech", label: "Marrakech", exists: true },
  { value: "Casablanca", label: "Casablanca", exists: true },
  { value: "Lisbon", label: "Lisbon", exists: true },
  { value: "Krakow", label: "Krakow", exists: true },
  { value: "Bucharest", label: "Bucharest", exists: true },
  { value: "Brasília", label: "Brasília", exists: true },
  { value: "Caracas", label: "Caracas", exists: true },
  { value: "Riyadh", label: "Riyadh", exists: true },
  { value: "Abu Dhabi", label: "Abu Dhabi", exists: true },
  { value: "Jakarta", label: "Jakarta", exists: true },
  { value: "Kuala Lumpur", label: "Kuala Lumpur", exists: true },
  { value: "Singapore", label: "Singapore", exists: true },
  { value: "Hanoi", label: "Hanoi", exists: true },
  { value: "Ho Chi Minh City", label: "Ho Chi Minh City", exists: true },
  { value: "Bogotá", label: "Bogotá", exists: true },
  { value: "Quito", label: "Quito", exists: true },
  { value: "La Paz", label: "La Paz", exists: true },
  { value: "San Juan", label: "San Juan", exists: true },
  { value: "Panama City", label: "Panama City", exists: true },
  { value: "San Diego", label: "San Diego", exists: true },
  { value: "Vancouver", label: "Vancouver", exists: true },
  { value: "Seattle", label: "Seattle", exists: true },
  { value: "Houston", label: "Houston", exists: true },
  { value: "Dallas", label: "Dallas", exists: true },
  { value: "Miami", label: "Miami", exists: true },
  { value: "Chicago", label: "Chicago", exists: true },
  { value: "Boston", label: "Boston", exists: true },
  { value: "Philadelphia", label: "Philadelphia", exists: true },
  { value: "Washington D.C.", label: "Washington D.C.", exists: true },
  { value: "Las Vegas", label: "Las Vegas", exists: true },
  { value: "Orlando", label: "Orlando", exists: true },
  { value: "Atlanta", label: "Atlanta", exists: true },
  { value: "Denver", label: "Denver", exists: true },
  { value: "Bagdad", label: "Bagdad", exists: true },
  { value: "Volga Bulgars", label: "Volga Bulgars", exists: true },
  { value: "Northland", label: "Northland", exists: true },
  { value: "Constantinople", label: "Constantinople", exists: true },
  { value: "Kiev", label: "Kiev", exists: true },
  { value: "Pacific Ocean", label: "Pacific Ocean", exists: true },
  { value: "DH-8 Habitat", label: "DH-8 Habitat", exists: true },
  { value: "Congo", label: "Congo", exists: true },
  { value: "South Pacific Ocean", label: "South Pacific Ocean", exists: true },
  { value: "Zinj", label: "Zinj", exists: true },
  { value: "Tangier", label: "Tangier", exists: true },
  { value: "Virunga region", label: "Virunga region", exists: true },
  { value: "Phoenix", label: "Phoenix", exists: true },
  { value: "Salt Lake City", label: "Salt Lake City", exists: true },
  { value: "Honolulu", label: "Honolulu", exists: true },
  { value: "Anchorage", label: "Anchorage", exists: true },
  { value: "Calgary", label: "Calgary", exists: true },
  { value: "Edmonton", label: "Edmonton", exists: true },
  { value: "Quebec City", label: "Quebec City", exists: true },
  { value: "Ottawa", label: "Ottawa", exists: true },
  { value: "Winnipeg", label: "Winnipeg", exists: true },
  { value: "Halifax", label: "Halifax", exists: true },
  { value: "St. John's", label: "St. John's", exists: true },
  { value: "Yellowknife", label: "Yellowknife", exists: true },
  { value: "Regina", label: "Regina", exists: true },
  { value: "Saskatoon", label: "Saskatoon", exists: true },
  { value: "Victoria", label: "Victoria", exists: true },
  { value: "Churchill", label: "Churchill", exists: true },
];
